### ISSUE TITLE
Persona details unclear: not sure if I actually own this (yet) or not

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#42] opened 2024-10-21 23:39 UTC
I think this might be related to #26 -- I'm looking at a persona that appears to be mine, but I'm not sure, because the Ask still shows that she's got 6 days plus pending (this character: https://beta.personacollective.ai/persona/690).
<img width="533" alt="Screenshot 2024-10-21 at 6 29 07 PM" src="https://github.com/user-attachments/assets/f6d63815-1875-4bb8-81e2-9ea119264ad7">
The persona's journal indicates that she was sent to the Vats/Stockyard, and I can't recall specifically if I tried to Infuse her, or what happened.  Anyway, this display is confusing: I don't know whether this Persona is actually mine or whether the Ask is still open and active or if this is the "Ask not cleared" bug or something.

**Comment by Jackalgirl** [comment] 2024-10-21 23:43
Likewise this hippy elf: https://beta.personacollective.ai/persona/1272 -- I have no idea if he's actually mine; the journal likewise mentions infusion and a stint in the Vats.  But the Ask is still showing 6 days, 16 hours (and some change), though the profile says "Approval required to place asks for this Persona".

**Comment by vessenes** [comment] 2024-10-31 17:28
This is a dupe of #26 -- however, to explain why you're seeing what you're seeing:

The ask system reports asks from former owners, so we show it in the UI. 

The approval checks if the current owner (which is you) has approved this persona for transfer, and you haven't yet, since they just transferred to you. 

The confusing Asks list will go away shortly and I think this should be only the typical amount of confusing at that point.

**Closed as completed by vessenes** 2024-10-31 17:28 UTC
