### ISSUE TITLE
Market Tab Not Updating

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#5] opened 2024-10-17 02:00 UTC
The market tab often does not update and remove items where the ask price has been met or an offer was completed and the NFT changes owners hands.  The NFT still stays up on the market tab no matter how much time I wait or how much I refresh.

**Comment by k1l1eN** [comment] 2024-10-17 02:11
null #13 Persona was originally put on the marketplace because toon put an offer up from my collective.  It appeared on the marketplace tab and I saw it.  I made an ask equal to the 250 she offered and the persona instantly transfered to her however it remains on the Market list with no ask but the original offer is still on it.

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/de875534-85d5-4a31-a152-71347d0921c8">

**Comment by vessenes** [comment] 2024-10-21 00:20
This is a duplicate of the various Ask bugs.

**Closed as completed by vessenes** 2024-10-21 00:20 UTC
Labels: duplicate
